using Amazon.KeyManagementService;
using Amazon.KeyManagementService.Model;

namespace Proteos.Encryption.AwsKms;

/// <summary>
/// The production <see cref="IKmsWrapClient"/>: a thin adapter over <see cref="IAmazonKeyManagementService"/>.
/// It uses symmetric KMS <c>Encrypt</c>/<c>Decrypt</c> with <c>SYMMETRIC_DEFAULT</c> — the customer master
/// key never leaves KMS — and pins the key id on both calls. It deliberately does <b>not</b> use
/// <c>GenerateDataKey</c>: the tenant master key already exists and is supplied for wrapping, rather than
/// being generated by KMS.
/// </summary>
internal sealed class KmsWrapClient : IKmsWrapClient
{
    private readonly IAmazonKeyManagementService _kms;

    public KmsWrapClient(IAmazonKeyManagementService kms)
    {
        _kms = kms ?? throw new ArgumentNullException(nameof(kms));
    }

    public async ValueTask<byte[]> EncryptAsync(string keyId, ReadOnlyMemory<byte> plaintextKey, CancellationToken cancellationToken)
    {
        using var plaintext = new MemoryStream(plaintextKey.ToArray());
        var request = new EncryptRequest
        {
            KeyId = keyId,
            Plaintext = plaintext,
            EncryptionAlgorithm = EncryptionAlgorithmSpec.SYMMETRIC_DEFAULT,
        };

        var response = await _kms.EncryptAsync(request, cancellationToken).ConfigureAwait(false);
        return response.CiphertextBlob.ToArray();
    }

    public async ValueTask<byte[]> DecryptAsync(string keyId, ReadOnlyMemory<byte> wrappedKey, CancellationToken cancellationToken)
    {
        using var ciphertext = new MemoryStream(wrappedKey.ToArray());
        var request = new DecryptRequest
        {
            KeyId = keyId,
            CiphertextBlob = ciphertext,
            EncryptionAlgorithm = EncryptionAlgorithmSpec.SYMMETRIC_DEFAULT,
        };

        var response = await _kms.DecryptAsync(request, cancellationToken).ConfigureAwait(false);
        return response.Plaintext.ToArray();
    }
}
